# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('sequence', models.IntegerField(primary_key=True, serialize=False)),
                ('assignment_name', models.CharField(max_length=100)),
                ('assignment_desc', models.TextField()),
                ('input_id', models.CharField(max_length=45)),
                ('input_ip', models.CharField(max_length=45)),
                ('input_date', models.TimeField(auto_now_add=True)),
                ('update_id', models.CharField(max_length=45)),
                ('update_ip', models.CharField(max_length=45)),
                ('update_date', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('professor_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('professor_name', models.CharField(max_length=45)),
                ('input_id', models.CharField(max_length=45)),
                ('input_ip', models.CharField(max_length=45)),
                ('input_date', models.TimeField(auto_now_add=True)),
                ('update_id', models.CharField(max_length=45)),
                ('update_ip', models.CharField(max_length=45)),
                ('update_date', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='signup_class',
            fields=[
                ('not_use_pri_key', models.AutoField(primary_key=True, serialize=False)),
                ('input_id', models.CharField(max_length=45)),
                ('input_ip', models.CharField(max_length=45)),
                ('input_date', models.TimeField(auto_now_add=True)),
                ('update_id', models.CharField(max_length=45)),
                ('update_ip', models.CharField(max_length=45)),
                ('update_date', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=45)),
                ('input_id', models.CharField(max_length=45)),
                ('input_ip', models.CharField(max_length=45)),
                ('input_date', models.TimeField(auto_now_add=True)),
                ('update_id', models.CharField(max_length=45)),
                ('update_ip', models.CharField(max_length=45)),
                ('update_date', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('pri_key', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
                ('semester', models.IntegerField()),
                ('subject_cd', models.CharField(max_length=20)),
                ('classes', models.CharField(max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('input_id', models.CharField(max_length=45)),
                ('input_ip', models.CharField(max_length=45)),
                ('input_date', models.TimeField(auto_now_add=True)),
                ('update_id', models.CharField(max_length=45)),
                ('update_ip', models.CharField(max_length=45)),
                ('update_date', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='subject_has_professor',
            fields=[
                ('not_use_pri_key', models.AutoField(primary_key=True, serialize=False)),
                ('represent_yn', models.BooleanField(default=False)),
                ('input_id', models.CharField(max_length=45)),
                ('input_ip', models.CharField(max_length=45)),
                ('input_date', models.TimeField(auto_now_add=True)),
                ('update_id', models.CharField(max_length=45)),
                ('update_ip', models.CharField(max_length=45)),
                ('update_date', models.TimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.professor')),
                ('sub_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.subject')),
            ],
        ),
        migrations.CreateModel(
            name='submit',
            fields=[
                ('not_use_pri_key', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.TextField()),
                ('comment', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('assign_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.subject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set([('year', 'semester', 'subject_cd', 'classes')]),
        ),
        migrations.AddField(
            model_name='signup_class',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.student'),
        ),
        migrations.AddField(
            model_name='signup_class',
            name='sub_seq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.subject'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='sub_seq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.subject'),
        ),
    ]
